ScouTeams/ScouTeams/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using ScouTeams.Areas.Identity.Data;
using ScouTeams.Data;
using ScouTeams.Models;
using ScouTeams.Services;
using ScouTeams.ViewModels;

namespace ScouTeams.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly UserManager<Scout> _userManager;
        private readonly SignInManager<Scout> _signInManager;
        private readonly ILogger<HomeController> _logger;
        private readonly ScouTDBContext _context;
        private IMailService _mailService;
        public const string SessionKeyType = "_Type";
        public const string SessionKeyOrganization = "_Organization";

        public HomeController(SignInManager<Scout> signInManager, ILogger<HomeController> logger, UserManager<Scout> userManager, ScouTDBContext context, IMailService mailService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _context = context;
            _mailService = mailService;
        }

        public async Task<IActionResult> ShowAssignments()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Nie znaleziono tego użytkownika");
            }

            List<Assignment> assignments = new List<Assignment>();
            var functions = _context.FunctionInOrganizations.Where(f => f.ScoutId == user.Id);
            if (functions != null)
            {
                foreach (var function in functions)
                {
                    if (function.DruzynaId == function.ZastepId && function.HufiecId == function.DruzynaId && function.DruzynaId == function.ChorągiewId)
                    {
                        Assignment assignment = new Assignment(TypeOrganization.KwateraGlowna, function.DruzynaId, "Kwatera Główna");
                        if (!assignments.Exists(x => x.TypeOrganization == assignment.TypeOrganization && x.OrganizationId == assignment.OrganizationId))
                            assignments.Add(assignment);
                    }
                    else if (function.ChorągiewId != -1)
                    {
                        var myAssignment = await _context.Choragiews.FirstOrDefaultAsync(x => x.ChoragiewId == function.ChorągiewId);
                        Assignment assignment = new Assignment(TypeOrganization.Choragiew, myAssignment.ChoragiewId, myAssignment.Name);
                        if (!assignments.Exists(x => x.TypeOrganization == assignment.TypeOrganization && x.OrganizationId == assignment.OrganizationId))
                            assignments.Add(assignment);
                    }
                    else if (function.HufiecId != -1)
                    {
                        var myAssignment = await _context.Hufiecs.FirstOrDefaultAsync(x => x.HufiecId == function.HufiecId);
                        Assignment assignment = new Assignment(TypeOrganization.Hufiec, myAssignment.HufiecId, myAssignment.Name);
                        if (!assignments.Exists(x => x.TypeOrganization == assignment.TypeOrganization && x.OrganizationId == assignment.OrganizationId))
                            assignments.Add(assignment);
                    }
                    else if (function.DruzynaId != -1)
                    {
                        var myAssignment = await _context.Druzynas.FirstOrDefaultAsync(x => x.DruzynaId == function.DruzynaId);
                        Assignment assignment = new Assignment(TypeOrganization.Druzyna, myAssignment.DruzynaId, myAssignment.Name);
                        if (!assignments.Exists(x => x.TypeOrganization == assignment.TypeOrganization && x.OrganizationId == assignment.OrganizationId))
                            assignments.Add(assignment);
                    }
                }
            }
            try
            {
                var zasteps = _context.UserZasteps.Where(x => x.ScoutId == user.Id);
                if (zasteps != null)
                {
                    foreach (var zastep in zasteps)
                    {
                        var myAssignment = await _context.Zastep.FirstOrDefaultAsync(x => x.ZastepId == zastep.ZastepId);
                        Assignment assignment = new Assignment(TypeOrganization.Zastep, zastep.ZastepId, myAssignment.Name);
                        if (!assignments.Exists(x => x.TypeOrganization == assignment.TypeOrganization && x.OrganizationId == assignment.OrganizationId))
                            assignments.Add(assignment);
                    }
                }
            }
            catch (Exception)
            {

            }
            return View(assignments);
        }

        public async Task<IActionResult> ShowContributions()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Nie znaleziono tego użytkownika");
            }

            return View(_context.Contributions.Where(c => c.ScoutId == user.Id).AsEnumerable().Reverse());
        }

        public async Task<IActionResult> ShowMeetings()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Nie znaleziono tego użytkownika");
            }
            List<MeetingWithPresence> meetingsWithPresence = new List<MeetingWithPresence>();

            var myPresences = _context.ScoutPresence.Where(s => s.ScoutId == user.Id);
            foreach (var presence in myPresences)
            {
                MeetingWithPresence meetingWithPresence = new MeetingWithPresence();
                meetingWithPresence.MeetingId = presence.MeetingId;
                var meeting = await _context.Meetings.FirstOrDefaultAsync(x => x.MeetingId == presence.MeetingId);
                if (meeting != null)
                {
                    var zastep = await _context.Zastep.FirstOrDefaultAsync(z => z.ZastepId == meeting.ZastepId);
                    if (zastep != null)
                    {
                        meetingWithPresence.ZastepName = zastep.Name;
                    }
                    else
                    {
                        meetingWithPresence.ZastepName = "Zastęp został rozwiązany.";
                    }
                    meetingWithPresence.Date = meeting.Date;

                }

                meetingWithPresence.Presence = presence.Presence;
                meetingsWithPresence.Add(meetingWithPresence);
            }

            return View(meetingsWithPresence.AsEnumerable().Reverse());
        }

        public async Task<IActionResult> ShowSkills()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Nie znaleziono tego użytkownika");
            }

            return View(_context.Skills.Where(s => s.ScoutId == user.Id).AsEnumerable().Reverse());
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Details(int id, TypeOrganization type)
        {
            HttpContext.Session.SetString(SessionKeyType, type.ToString());
            HttpContext.Session.SetInt32(SessionKeyOrganization, id);
            switch (type)
            {
                case TypeOrganization.KwateraGlowna:
                    return RedirectToAction(nameof(ShowKwateraGlowna));
                case TypeOrganization.Choragiew:
                    return RedirectToAction(nameof(ShowChoragiew));
                case TypeOrganization.Hufiec:
                    return RedirectToAction(nameof(ShowHufiec));
                case TypeOrganization.Druzyna:
                    return RedirectToAction(nameof(ShowDruzyna));
                case TypeOrganization.Zastep:
                    return RedirectToAction(nameof(ShowZastep));
                default:
                    return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> ShowKwateraGlowna(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            var type = HttpContext.Session.GetString(SessionKeyType);
            var id = HttpContext.Session.GetInt32(SessionKeyOrganization);
            if (type == null || id == null || type != TypeOrganization.KwateraGlowna.ToString())
            {
                return RedirectToAction(nameof(Index));
            }
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Nie znaleziono tego użytkownika");
            }

            var tmp = await _context.KwateraGlowna.FirstOrDefaultAsync(x => x.KwateraGlownaId == id);
            if (tmp == null)
            {
                return NotFound($"Nie można załadować Kwatery Głównej z tym identyfikatorem.");
            }
            var myFunctionInKG = await _context.FunctionInOrganizations.FirstOrDefaultAsync(f => f.ScoutId == user.Id && f.ChorągiewId == id && f.HufiecId == id && f.DruzynaId == id && f.ZastepId == id);
            if (myFunctionInKG == null)
            {
                return RedirectToAction(nameof(ShowAssignments));
            }

            var myScouts = new List<ScoutViewModel>();

ScouTeams/ScouTeams/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScouTeams.Data;
using ScouTeams.Models;

namespace ScouTeams.Controllers
{
    [Authorize]
    public class SkillsController : Controller
    {
        private readonly ScouTDBContext _context;

        public SkillsController(ScouTDBContext context)
        {
            _context = context;
        }

        // GET: Skills
        public async Task<IActionResult> Index(string scoutId)
        {
            ViewData["scoutId"] = scoutId;
            return View(await _context.Skills.Where(s => s.ScoutId == scoutId).ToListAsync());
        }

        // GET: Skills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = await _context.Skills
                .FirstOrDefaultAsync(m => m.SkillId == id);
            if (skill == null)
            {
                return NotFound();
            }

            return View(skill);
        }

        // GET: Skills/Create
        public IActionResult Create(string id)
        {
            Skill skill = new Skill();
            skill.ScoutId = id;
            ViewData["scoutId"] = id;
            return View(skill);
        }

        // POST: Skills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SkillId,Difficulty,ScoutId,Name")] Skill skill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(skill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { scoutId = skill.ScoutId });
            }
            ViewData["scoutId"] = skill.ScoutId;
            return View(skill);
        }

        // GET: Skills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = await _context.Skills.FindAsync(id);
            if (skill == null)
            {
                return NotFound();
            }
            return View(skill);
        }

        // POST: Skills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SkillId,Difficulty,ScoutId,Name")] Skill skill)
        {
            if (id != skill.SkillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(skill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkillExists(skill.SkillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { scoutId = skill.ScoutId });
            }
            return View(skill);
        }

        // GET: Skills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = await _context.Skills
                .FirstOrDefaultAsync(m => m.SkillId == id);
            if (skill == null)
            {
                return NotFound();
            }

            return View(skill);
        }

        // POST: Skills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var skill = await _context.Skills.FindAsync(id);
            _context.Skills.Remove(skill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SkillExists(int id)
        {
            return _context.Skills.Any(e => e.SkillId == id);
        }
    }
}

ScouTeams/ScouTeams/Views/Home/AddFunctionScout.cshtml
@model ScouTeams.ViewModels.ScoutViewModel
@using ScouTeams.ViewModels
@{
    ViewData["Title"] = "AddFunctionScout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="AddFunctionScout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ThisOrganizationId" />
            <input type="hidden" asp-for="ThisTypeOrganization" />
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="functionName" class="control-label"></label>
                <select asp-for="functionName"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<FunctionName>()">
                    <option>Wybierz jeden...</option>
                </select>
                <span asp-validation-for="functionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Nadaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<p>
    @if (ViewData["TypeOrganization"].ToString() == TypeOrganization.KwateraGlowna.ToString())
    {
        <a asp-action="ShowKwateraGlowna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Choragiew.ToString())
    {
        <a asp-action="ShowChoragiew">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Hufiec.ToString())
    {
        <a asp-action="ShowHufiec">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Druzyna.ToString())
    {
        <a asp-action="ShowDruzyna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Zastep.ToString())
    {
        <a asp-action="ShowZastep">Anuluj</a>
    }
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScouTeams/ScouTeams/Views/Home/EditInstructorDegree.cshtml
@model ScouTeams.ViewModels.ScoutViewModel
@using ScouTeams.Areas.Identity.Data;
@using ScouTeams.ViewModels

@{
    ViewData["Title"] = "EditInstructorDegree";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditInstructorDegree">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="ScoutDegree" class="control-label"></label>
                <input asp-for="ScoutDegree" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="InstructorDegree" class="control-label"></label>
                <select asp-for="InstructorDegree"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<InstructorDegree>()">
                    <option>Wybierz jeden...</option>
                </select>
                <span asp-validation-for="InstructorDegree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Nadaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<p>
    @if (ViewData["TypeOrganization"].ToString() == TypeOrganization.KwateraGlowna.ToString())
    {
        <a asp-action="ShowKwateraGlowna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Choragiew.ToString())
    {
        <a asp-action="ShowChoragiew">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Hufiec.ToString())
    {
        <a asp-action="ShowHufiec">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Druzyna.ToString())
    {
        <a asp-action="ShowDruzyna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Zastep.ToString())
    {
        <a asp-action="ShowZastep">Anuluj</a>
    }
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScouTeams/ScouTeams/Views/Home/EditScoutDegree.cshtml
@model ScouTeams.ViewModels.ScoutViewModel
@using ScouTeams.Areas.Identity.Data;
@using ScouTeams.ViewModels
@{
    ViewData["Title"] = "EditScoutDegree";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditScoutDegree">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" disabled />
            </div>
            <div class="form-group">
                <label asp-for="ScoutDegree" class="control-label"></label>
                <select asp-for="ScoutDegree"
                        class="form-control"
                        asp-items="Html.GetEnumSelectList<ScoutDegree>()">
                    <option>Wybierz jeden...</option>
                </select>
                <span asp-validation-for="ScoutDegree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InstructorDegree" class="control-label"></label>
                <input asp-for="InstructorDegree" class="form-control" disabled />
            </div>
            <div class="form-group">
                <input type="submit" value="Nadaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<p>
    @if (ViewData["TypeOrganization"].ToString() == TypeOrganization.KwateraGlowna.ToString())
    {
        <a asp-action="ShowKwateraGlowna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Choragiew.ToString())
    {
        <a asp-action="ShowChoragiew">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Hufiec.ToString())
    {
        <a asp-action="ShowHufiec">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Druzyna.ToString())
    {
        <a asp-action="ShowDruzyna">Anuluj</a>
    }
    else if (ViewData["TypeOrganization"].ToString() == TypeOrganization.Zastep.ToString())
    {
        <a asp-action="ShowZastep">Anuluj</a>
    }
</p>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScouTeams/ScouTeams/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Witaj na stronie ScouTeams!</h1>
    <h2>
        W pasku nawigacyjnym znajdziesz podstrony z informacjami odnośnie swojego konta.
    </h2>
    <h3>
        Wciśnięcie słowa ScouTeams przeniesie Cię do obecnej strony. Jeśli chcesz zobaczyć Swoje składki, naciśnij słowo Składki.
        W zakładce Przydziały znajdziesz zastępy, do których należysz oraz struktury, w których posiadasz funkcje. 
        Jeżeli nie posiadasz żadnego przydziału, poproś przełożonego o dodanie. 
        Do przeglądu i edycji swoich danych osobowych lub szczegółów dotyczących konta, np. zmiany hasła, służy zakładka z Twoim adresem e-mail. 
    </h3>
    <p>Aplikacja ta została stworzona przez Pawła Puczyłowskiego w ramach pisania pracy inżynierskiej.</p>
    <p>
        System powstał na Wydziale Informatyki Politechniki Białostockiej.
    </p>
</div>

ScouTeams/ScouTeams/Views/Home/ShowContributions.cshtml
@model IEnumerable<ScouTeams.Models.Contribution>

@{
    ViewData["Title"] = "ShowContributions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Amount) zł
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
}
    </tbody>
</table>

ScouTeams/ScouTeams/Views/Home/ShowDruzyna.cshtml
@model PaginatedList<ScouTeams.ViewModels.ScoutViewModel>

@{
    ViewData["Title"] = "ShowDruzyna";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["OrganizationName"]</h1>

<p>
    <a asp-action="ShowScoutsForRecruitment">Dodaj harcerza</a> |
    @Html.ActionLink("Pobierz plik Excel", "ExportData", new { id = ViewData["OrganizationID"], typeOrganization = ViewData["TypeOrganization"], name = ViewData["OrganizationName"] }) |
    @Html.ActionLink("Pokaż zastępy", "ShowSubordinateUnits", new { OrganizationId = ViewData["OrganizationID"], type = ViewData["TypeOrganization"] }) |
    @Html.ActionLink("Wyślij Email do wszystkich", "SendEmailToScouts", new { id = ViewData["OrganizationID"], typeOrganization = ViewData["TypeOrganization"] })
</p>
<form asp-action="ShowDruzyna" method="get">
    <div class="form-actions no-color">
        <p>
            Znajdź po nazwie: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Szukaj" class="btn btn-default" /> |
            <a asp-action="ShowDruzyna">Wróć do pełnej listy</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Imię
            </th>
            <th>
                <a asp-action="ShowDruzyna" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Nazwisko</a>
            </th>
            <th>
                Funkcja
            </th>
            <th>
                E-mail
            </th>
            <th>
                <a asp-action="ShowDruzyna" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Data urodzenia</a>
            </th>
            <th>
                Opłacone składki
            </th>
            <th>
                Stopień harcerski
            </th>
            <th>
                Stopień instruktorski
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Functions) <br />
                    @Html.ActionLink("Nadaj funkcję", "AddFunctionScout", new { scoutId = item.Id, OrganizationId = ViewData["OrganizationID"], type = ViewData["TypeOrganization"] }) |
                    @Html.ActionLink("Odbierz funkcję", "Index", "FunctionInOrganizations", new { scoutId = item.Id, OrganizationId = ViewData["OrganizationID"], type = ViewData["TypeOrganization"] })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaidContributions)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScoutDegree) <br />
                    @Html.ActionLink("Edytuj stopień harcerski", "EditScoutDegree", new { scoutId = item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InstructorDegree) <br />
                    @Html.ActionLink("Edytuj stopień instruktorski", "EditInstructorDegree", new { scoutId = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Sprawności", "Index", "Skills", new { scoutId = item.Id }) |
                    @Html.ActionLink("Składki", "Index", "Contributions", new { scoutId = item.Id, type = ViewData["TypeOrganization"] }) |
                    @Html.ActionLink("Wyślij Email", "SendEmailToScout", new { mail = item.Email }) |
                    @if (String.IsNullOrEmpty(item.Functions))@Html.ActionLink("Usuń", "DeleteScout", new { scoutId = item.Id, OrganizationId = ViewData["OrganizationID"], type = ViewData["TypeOrganization"] }, new { onclick = "return confirm('Na pewno usunąć z drużyny?');" })
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="ShowDruzyna"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Wcześniejsza
</a>
<a asp-action="ShowDruzyna"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Następna
</a>

ScouTeams/ScouTeams/Views/Home/ShowSkills.cshtml
@model IEnumerable<ScouTeams.Models.Skill>

@{
    ViewData["Title"] = "ShowSkills";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
}
    </tbody>
</table>